http:
  routers:
    dashboard-router:
      entryPoints:
      - web
      priority: 1
      rule: Host(`localhost`)
      service: dashboard-service
    demo-app:
      entryPoints:
      - web
      rule: Host(`demo-app.localhost`)
      service: demo-app
    test:
      entryPoints:
      - web
      rule: Host(`test.localhost`)
      service: test
  services:
    dashboard-service:
      loadBalancer:
        servers:
        - url: http://paas_api:8000
    demo-app:
      loadBalancer:
        servers:
        - url: http://app-demo-app:80
    test:
      loadBalancer:
        servers:
        - url: http://app-test:80
