http:
  routers:
    auth-router:
      entryPoints:
      - web
      priority: 10
      rule: Host(`localhost`) && (PathPrefix(`/api/register`) || PathPrefix(`/api/login`)
        || PathPrefix(`/api/me`) || PathPrefix(`/api/auth`))
      service: auth-service
    dashboard-router:
      entryPoints:
      - web
      priority: 1
      rule: Host(`localhost`)
      service: auth-service
    deploy-router:
      entryPoints:
      - web
      priority: 10
      rule: Host(`localhost`) && (PathPrefix(`/api/deploy`) || PathPrefix(`/api/deployments`)
        || PathPrefix(`/api/status`) || PathPrefix(`/api/webhook`) || PathPrefix(`/api/projects`)
        || PathPrefix(`/api/internal`))
      service: deploy-service
    github-router:
      entryPoints:
      - web
      priority: 10
      rule: Host(`localhost`) && PathPrefix(`/api/github`)
      service: github-service
    omertank36-testapp:
      entryPoints:
      - web
      rule: Host(`omertank36-testapp.localhost`)
      service: omertank36-testapp
    omertank37-testapp:
      entryPoints:
      - web
      rule: Host(`omertank37-testapp.localhost`)
      service: omertank37-testapp
    test2:
      entryPoints:
      - web
      rule: Host(`test2.localhost`)
      service: test2
    testapp:
      entryPoints:
      - web
      rule: Host(`testapp.localhost`)
      service: testapp
  services:
    auth-service:
      loadBalancer:
        servers:
        - url: http://auth-service:8001
    deploy-service:
      loadBalancer:
        servers:
        - url: http://deploy-service:8003
    github-service:
      loadBalancer:
        servers:
        - url: http://github-service:8002
    omertank36-testapp:
      loadBalancer:
        servers:
        - url: http://omertank36_testapp:80
    omertank37-testapp:
      loadBalancer:
        servers:
        - url: http://omertank37_testapp:80
    test2:
      loadBalancer:
        servers:
        - url: http://app-test2:80
    testapp:
      loadBalancer:
        servers:
        - url: http://app-testapp:80
